#!/sbin/sh

# fixing CPU clocks to avoid issues in recovery
echo 1024000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 122000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq

echo 0 > /sys/class/android_usb/android0/enable
echo 18D1 > /sys/class/android_usb/android0/idVendor 
echo D002 > /sys/class/android_usb/android0/idProduct
echo adb > /sys/class/android_usb/android0/functions
echo 1 > /sys/class/android_usb/android0/enable
stop adbd

# trigger red LED
echo '255' > /sys/class/leds/red/brightness
# trigger button-backlight
echo '255' > /sys/class/leds/button-backlight/brightness
# trigger vibrator
echo "250" > /sys/class/timed_output/vibrator/enable

cat /dev/input/event2 > /dev/keycheck&
sleep 3

# trigger blue LED
echo '0' > /sys/class/leds/red/brightness
# trigger button-backlight
echo '0' > /sys/class/leds/button-backlight/brightness

kill -9 $!
